TAKU_API_SERVICE_PORT=3010
TAKU_API_SERVICE_DOMAIN=api.taku.lat
TAKU_WA_SERVICE_PORT=3101
TAKU_WA_SERVICE_DOMAIN=api.wa.taku.lat
TAKU_BOT_SERVICE_PORT=3111
TAKU_BOT_SERVICE_DOMAIN=api.bot.taku.lat
TAKU_WEB_SERVICE_PORT=3121
TAKU_WEB_SERVICE_DOMAIN=app.taku.lat
